routes/web.php
    Route::get('/primeiro-acesso', 'ContaUsuarioController@primeiroAcesso')->name('conta-usuario.primeiro-acesso');
    Route::get('/primeiro-acesso/lista-enderecos-empresa', 'ContaUsuarioController@listarEnderecosEmpresa')->name('conta-usuario.listar-endereco-empresa');
    Route::post('/primeiro-acesso/confirmar-empresa', 'ContaUsuarioController@confirmarEmpresa')->name('conta-usuario.confirmar-empresa');
    Route::post('/primeiro-acesso/cadastrar-empresa', 'ContaUsuarioController@cadastrarEmpresa')->name('conta-usuario.pre-cadastro-empresa');
    Route::post('/primeiro-acesso/cadastrar-endereco', 'ContaUsuarioController@adicionarEndereco')->name('conta-usuario.pre-cadastro-endereco');


});



Auth::routes();


Route::prefix('admin')->name('admin.')->namespace('Admin')->group(function () {
    Auth::routes();
    //Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::middleware('auth:admin')->group(function () {

        Route::get('/', 'DashboardController@index')->name('dashboard.index');

        #Usuarios
        Route::match(['get', 'post'],'/usuarios/', 'UsuarioController@index')->name('usuarios.index');
        Route::get('/usuarios/novo', 'UsuarioController@create')->name('usuarios.novo');
        Route::get('/usuarios/editar/{id}', 'UsuarioController@edit')->name('usuarios.editar');
        Route::post('/usuarios/gravar', 'UsuarioController@store')->name('usuarios.gravar');
        Route::post('/usuarios/atualizar/{id}', 'UsuarioController@update')->name('usuarios.atualizar');
        Route::get('/usuarios/excluir/{id}', 'UsuarioController@destroy')->name('usuarios.excluir');

        //Empresa
        Route::match(['get', 'post'],'/empresas/', 'EmpresaController@index')->name('empresas.index');
        Route::match(['get', 'post'],'/empresas/pre-cadastro', 'EmpresaController@preCadastro')->name('empresas.pre-cadastro');

        Route::get('/empresas/novo', 'EmpresaController@create')->name('empresas.novo');
        Route::get('/empresas/editar/{id}', 'EmpresaController@edit')->name('empresas.editar');
        Route::get('/empresas/ativar/{id}', 'EmpresaController@ativar')->name('empresas.ativar');
        Route::post('/empresas/gravar', 'EmpresaController@store')->name('empresas.gravar');
        Route::post('/empresas/atualizar/{id}', 'EmpresaController@update')->name('empresas.atualizar');
        Route::get('/empresas/excluir/{id}', 'EmpresaController@destroy')->name('empresas.excluir');

        #EnderecoEmpresa
        Route::post('/empresas/novo-endereco', 'EmpresaController@storeEndereco')->name('empresas.endereco.gravar');
        Route::post('/empresas/atualizar-endereco', 'EmpresaController@updateEndereco')->name('empresas.endereco.atualizar');
        Route::get('/empresas/excluir-endereco/{id}', 'EmpresaController@destroyEndereco')->name('empresas.endereco.excluir');

        #cupons
        Route::match(['get', 'post'], '/cupom', 'CupomController@index')->name('cupom.index');
        Route::get('/cupom/novo', 'CupomController@create')->name('cupom.novo');
        Route::get('/cupom/editar/{id}', 'CupomController@edit')->name('cupom.editar');
        Route::post('/cupom/gravar', 'CupomController@store')->name('cupom.gravar');
        Route::post('/cupom/atualizar/{id}', 'CupomController@update')->name('cupom.atualizar');
        Route::get('/cupom/excluir/{id}', 'CupomController@destroy')->name('cupom.excluir');

        //Descontos

        #Por frequência
        Route::get('/descontos', 'DescontoController@index')->name('desconto.index');
        Route::get('/descontos/novo', 'DescontoController@create')->name('desconto.novo');
        Route::get('/descontos/editar/{id}', 'DescontoController@edit')->name('desconto.editar');
        Route::post('/descontos/gravar', 'DescontoController@store')->name('desconto.gravar');
        Route::post('/descontos/atualizar/{id}', 'DescontoController@update')->name('desconto.atualizar');
        Route::get('/descontos/excluir/{id}', 'DescontoController@destroy')->name('desconto.excluir');

        #Combo
        Route::get('/combos', 'ComboController@index')->name('combo.index');
        Route::get('/combos/novo', 'ComboController@create')->name('combo.novo');
        Route::get('/combos/editar/{id}', 'ComboController@edit')->name('combo.editar');
        Route::post('/combos/gravar', 'ComboController@store')->name('combo.gravar');
        Route::post('/combos/atualizar/{id}', 'ComboController@update')->name('combo.atualizar');
        Route::get('/combos/excluir/{id}', 'ComboController@destroy')->name('combo.excluir');

        Route::get('/combos/{id}/tabela-preco', 'TabelaPrecoController@indexCombo')->name('combo.tabela-preco');
        Route::post('/combos/{id}/tabela-preco', 'TabelaPrecoController@storeCombo')->name('combo.tabela-preco.salvar');
        Route::get('/combos/{idEmpresa}/tabela-preco/{idCombo}/excluir', 'TabelaPrecoController@destroyCombo')->name('combo.tabela-preco.excluir');


        //Relatorios
        Route::get('/cupom/utilizacao/{id}', 'CupomController@utilizacao')->name('cupom.utilizacao');

        #Locais de Entrega
        Route::match(['get', 'post'],'/locais-entrega', 'LocalEntregaController@index')->name('local-entrega.index');
        Route::get('/locais-entrega/novo', 'LocalEntregaController@create')->name('local-entrega.novo');
        Route::get('/locais-entrega/editar/{id}', 'LocalEntregaController@edit')->name('local-entrega.editar');
        Route::post('/locais-entrega/gravar', 'LocalEntregaController@store')->name('local-entrega.gravar');
        Route::post('/locais-entrega/atualizar/{id}', 'LocalEntregaController@update')->name('local-entrega.atualizar');
        Route::get('/locais-entrega/excluir/{id}', 'LocalEntregaController@destroy')->name('local-entrega.excluir');

        #Pagamentos
        Route::get('/pagamentos', 'PagamentoController@index')->name('pagamento.index');
        Route::get('/pagamentos/novo', 'PagamentoController@create')->name('pagamento.novo');
        Route::get('/pagamentos/editar/{id}', 'PagamentoController@edit')->name('pagamento.editar');
        Route::post('/pagamentos/gravar', 'PagamentoController@store')->name('pagamento.gravar');
        Route::post('/pagamentos/atualizar/{id}', 'PagamentoController@update')->name('pagamento.atualizar');
        Route::get('/pagamentos/excluir/{id}', 'PagamentoController@destroy')->name('pagamento.excluir');

        #Horarios de Entrega
        Route::get('/horarios-entrega', 'HorarioEntregaController@index')->name('horarios-entrega.index');
        Route::get('/horarios-entrega/novo', 'HorarioEntregaController@create')->name('horarios-entrega.novo');
        Route::get('/horarios-entrega/editar/{id}', 'HorarioEntregaController@edit')->name('horarios-entrega.editar');
        Route::post('/horarios-entrega/gravar', 'HorarioEntregaController@store')->name('horarios-entrega.gravar');
        Route::post('/horarios-entrega/atualizar/{id}', 'HorarioEntregaController@update')->name('horarios-entrega.atualizar');
        Route::get('/horarios-entrega/excluir/{id}', 'HorarioEntregaController@destroy')->name('horarios-entrega.excluir');

        #FAQ
        Route::match(['get', 'post'],'/faq', 'FAQController@index')->name('faq.index');
        Route::get('/faq/novo', 'FAQController@create')->name('faq.novo');
        Route::get('/faq/editar/{id}', 'FAQController@edit')->name('faq.editar');
        Route::post('/faq/gravar', 'FAQController@store')->name('faq.gravar');
        Route::post('/faq/atualizar/{id}', 'FAQController@update')->name('faq.atualizar');
        Route::get('/faq/excluir/{id}', 'FAQController@destroy')->name('faq.excluir');


        #newsletter
        Route::match(['get', 'post'],'/newsletter/', 'NewsletterController@index')->name('newsletter.index');
        Route::get('/newsletter/download', 'NewsletterController@download')->name('newsletter.download');

        #BuscasCEP
        Route::match(['get', 'post'],'/buscascep/', 'BuscaCEPController@index')->name('buscascep.index');
        Route::get('/buscascep/download', 'BuscaCEPController@download')->name('buscascep.download');

        #Cliente
        Route::match(['get', 'post'],'/clientes/', 'ClienteController@index')->name('clientes.index');
        Route::get('/clientes/novo', 'ClienteController@create')->name('clientes.novo');
        Route::get('/clientes/editar/{id}', 'ClienteController@edit')->name('clientes.editar');
        Route::post('/clientes/gravar', 'ClienteController@store')->name('clientes.gravar');
        Route::post('/clientes/atualizar', 'ClienteController@update')->name('clientes.atualizar');
        Route::get('/clientes/excluir/{id}', 'ClienteController@destroy')->name('clientes.excluir');
        Route::get('/clientes/download', 'ClienteController@download')->name('clientes.download');

        #Categoria Acompanhamento
        Route::get('/categorias-acompanhamento/', 'CategoriaAcompanhamentoController@index')->name('categoria-acompanhamento.index');
        Route::get('/categoria-acompanhamento/novo', 'CategoriaAcompanhamentoController@create')->name('categoria-acompanhamento.novo');
        Route::get('/categoria-acompanhamento/editar/{id}', 'CategoriaAcompanhamentoController@edit')->name('categoria-acompanhamento.editar');
        Route::post('/categoria-acompanhamento/gravar', 'CategoriaAcompanhamentoController@store')->name('categoria-acompanhamento.gravar');
        Route::post('/categoria-acompanhamento/atualizar', 'CategoriaAcompanhamentoController@update')->name('categoria-acompanhamento.atualizar');
        Route::get('/categoria-acompanhamento/excluir/{id}', 'CategoriaAcompanhamentoController@destroy')->name('categoria-acompanhamento.excluir');

        #Acompanhamento
        Route::match(['get', 'post'],'/acompanhamentos/', 'AcompanhamentoController@index')->name('acompanhamento.index');
        Route::get('/acompanhamento/novo', 'AcompanhamentoController@create')->name('acompanhamento.novo');

app/Http/Controllers/Admin/DescontoController.php
<?php

namespace AsBentas\Http\Controllers\Admin;

use Illuminate\Http\Request;
use AsBentas\Http\Controllers\Controller;
use AsBentas\Model\DescontoProgressivo;
use AsBentas\Http\Requests\Admin\DescontoRequest;

class DescontoController extends Controller
{
    public function index()
    {

        $descontos = DescontoProgressivo::orderBy('dia', 'asc')->paginate(10);

        return view('admin.desconto.index', ['descontos' => $descontos]);

    }

    public function create()
    {
        return view('admin.desconto.formulario', ['desconto' => new DescontoProgressivo()]);
    }

    public function edit($id)
    {
        $desconto = DescontoProgressivo::findOrFail($id);


        return view('admin.desconto.formulario', ['desconto' => $desconto]);
    }

    public function store(DescontoRequest $request)
    {
        $desconto = DescontoProgressivo::create($request->except( [ "_token" ] ));

        if ($desconto) {
            flash('Desconto salvo com sucesso.')->success();
            return redirect()->route('admin.desconto.index');
        }
        else{
            flash('Erro ao salvar Desconto.')->danger();
            return redirect()->route('admin.desconto.index');
        }

    }

    public function update(DescontoRequest $request)
    {

        $desconto = DescontoProgressivo::updateOrCreate(['id' => $request->id], $request->except( [ "_token" ] ));

        flash('Desconto atualizado com sucesso.')->success();

        return redirect()->route('admin.desconto.index');

    }


    public function destroy($id)
    {


        $desconto = DescontoProgressivo::findOrFail($id);
        $desconto->delete();

        flash('Desconto removido com sucesso.')->success();

        return redirect()->route('admin.desconto.index');

    }
}

resources/views/admin/desconto/formulario.blade.php
@extends('admin.layouts.admin')

@section('page-title')
    Gestão de Descontos
@endsection

@section('content')
    <form class="validate"
          action="{{ $desconto->id  ? route('admin.desconto.atualizar', ['id' => $desconto->id]) : route('admin.desconto.gravar') }}"
          method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-12">
                
                <div class="panel panel-default">
                    <div class="panel-heading panel-heading-transparent">
                        <strong>Registro de Desconto</strong>
                    </div>

                    <div class="panel-body">

                        <fieldset>
                            <!-- required [php action request] -->
                            {{ csrf_field() }}
                            <input type="hidden" name="id" value="{{ $desconto->id }}">

                            <div class="row">
                                <div class="form-group ">
                                    <div class="col-md-2 col-sm-2 {{ $errors->has('dia') ? 'has-error' : '' }}">
                                        <label>Dia *</label>
                                        <input type="number" name="dia" id="dia" value="{{ old('dia', $desconto->dia) }}"
                                               class="form-control required">
                                        @if($errors->has('dia'))
                                            <span class="help-inline text-red">{{ $errors->first('dia') }}</span>
                                        @endif
                                    </div>
                                    <div class="col-md-3 col-sm-3 {{ $errors->has('desconto') ? 'has-error' : '' }}">
                                        <label>Desconto *</label>
                                        <input type="text" name="desconto" id="desconto" value="{{ old('desconto', $desconto->desconto) }}"
                                               class="form-control required percent">
                                        @if($errors->has('desconto'))
                                            <span class="help-inline text-red">{{ $errors->first('desconto') }}</span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group {{ $errors->has('valor') ? 'has-error' : '' }}">
                                    
                                </div>
                            </div>

                            


                        </fieldset>

                        <div class="row text-center">
                            <div class="col-md-12 margin-top-30">
                                <button class="btn btn-primary" type="submit">
                                    Salvar
                                </button>
                                <a class="btn btn-warning" href="{{ route('admin.desconto.index') }}">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </form>
@endsection

@section('stylesheets')
    <link href="/assets/plugins/pikaday/pikaday.css" rel="stylesheet">
    <link href="/assets/plugins/selectize/css/selectize.css" rel="stylesheet">
    <link href="/assets/plugins/selectize/css/selectize.bootstrap3.css" rel="stylesheet">
@endsection

@section('javascripts')
    <script src="/assets/plugins/pikaday/pikaday.js"></script>
    <script src="/assets/plugins/selectize/js/standalone/selectize.min.js"></script>
    <script src="/assets/js/admin/desconto_form.js"></script>
@endsection

resources/views/admin/desconto/index.blade.php
@extends('admin.layouts.admin')
@section('page-title')
    Gestão de Descontos
@endsection
@section('content')
    <div id="panel-1" class="panel panel-default">
        <div class="panel-heading">
            <span class="title elipsis">
                <strong>Listagem</strong>
            </span>
        </div>

        <!-- panel content -->
        <div class="panel-body">
            @include('flash::message')
            <div class="table-responsive">
                <table class="table table-bordered table-vertical-middle nomargin" id="tabela-desconto">
                    <thead>
                    <tr>
                        <th class="width-30">Dia</th>
                        <th >Valor</th>
                        <th class="width-400"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($descontos as $desconto)
                        <tr>
                        
                            <td>
                                {{ $desconto->dia}}
                            </td>
                            <td>
                                {{ $desconto->desconto}}%
                            </td>
                            <td class="text-center">
                                <a href="{{ route('admin.desconto.editar', [ 'id' => $desconto->id] ) }}" class="btn btn-default btn-xs">
                                    <i class="fa fa-edit white"></i> Editar
                                </a>
                                <a href="#" class="btn btn-default btn-xs excluir-desconto" data-url="{{ route('admin.desconto.excluir', [ 'id' => $desconto->id] ) }}">
                                    <i class="fa fa-times white"></i> Remover
                                </a>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
            <div class="text-center">
                {{ $descontos->links() }}
            </div>
        </div>
        <!-- /panel content -->

        <!-- panel footer -->
        <div class="panel-footer">


            <div class="text-left">
                <a href="{{ route('admin.desconto.novo') }}" class="btn btn-primary">
                    Novo Item
                </a>
            </div>

            <!-- /pre code -->

        </div>
        <!-- /panel footer -->

    </div>
@endsection

@section('javascripts')
    <script src="/assets/js/admin/desconto_index.js"></script>
@endsection

resources/views/admin/desconto/utilizacao.blade.php
@extends('admin.layouts.admin')
@section('page-title')
    Gestão de Cupons
@endsection
@section('content')

    <div id="" class="panel panel-default">
        

        <!-- panel content -->
        <div class="panel-body">
            <div class="row">
                <div class="form-group">
                    <div class="col-md-3 col-sm-3">
                        <label>Código </label>
                        <input type="text" value="{{ $cupom->codigo }}" class="form-control" disabled>
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <label>Expira em </label>
                        <input type="text" value="{{ $cupom->data_expiracao ? $cupom->data_expiracao->format('d/m/Y') : null}}" class="form-control" disabled>
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <label>Tipo</label>
                        <input type="text" value="{{ $cupom->tipo == '$' ? 'Valor' : 'Porcentagem' }}" class="form-control" disabled>
                    </div>
                    <div class="col-md-3 col-sm-3">
                        <label>Aplicado em</label>
                        <input type="text" value="{{ $cupom->tipo_cupom == 0 ? 'Campanha' : 'Único' }}" class="form-control" disabled>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="panel-1" class="panel panel-default">
        <div class="panel-heading">
            <span class="title elipsis">
                <strong>Listagem de Utilizações</strong>
            </span>
        </div>

        <!-- panel content -->
        <div class="panel-body">
            
            <div class="table-responsive">
                <table class="table table-bordered table-vertical-middle nomargin" id="tabela-cupom">
                    <thead>
                    <tr>
                        <th>Usuário</th>
                        <th>Data Utilização</th>
                        <th>Pedido</th>
                        
                        <th>Valor Pedido</th>
                        
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($cupom->pedidos as $pedido)
                        <tr>
                            <td>
                                {{ $pedido->pedido->usuario->name }}
                            </td>
                            <td>
                                {{ $pedido->created_at->format('d/m/Y') }}
                            </td>
                            <td>
                                {{ $pedido->pedido->id }}
                            </td>
                            <td>
                                {{ $pedido->pedido->valor_total }}
                            </td>
                            
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>

        </div>
        <!-- /panel content -->

        <!-- panel footer -->
        <div class="panel-footer">


            

            <!-- /pre code -->

        </div>
        <!-- /panel footer -->

    </div>
@endsection

@section('javascripts')
    <script src="/assets/js/admin/cupom_index.js"></script>
@endsection